object Versions {

    const val coreKtx = "1.12.0"
    const val appcompat = "1.6.1"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val activityCompose = "1.8.0"
    const val composeBom = "2023.10.01"
    const val composeUi = "1.5.4"
    const val material3 = "1.1.2"
    const val materialExtended = "1.5.4"
    const val junit = "4.13.2"
    const val testJunit = "1.1.5"
    const val espressoCore = "3.5.1"
    const val navigationCompose = "2.7.5"
    const val lifecycleViewModelKtx = "2.6.1"
    const val hilt = "2.48"
    const val hiltCompiler = "1.1.0-alpha01"
    const val hiltNavigationCompose = "1.1.0"
    const val retrofit = "2.9.0"
    const val okHttp = "5.0.0-alpha.2"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.8.1"
    const val coroutines = "1.7.3"
    const val splashScreen = "1.0.0-alpha01"
}